### ISSUE TITLE
Could not find artifact org.highmed.dsf:dsf-bpe-process-base:jar:tests:0.4.0-SNAPSHOT

### ISSUE THREAD

**Issue by janprill** [highmed/example-processes#2]
Hello DSF-Team,

I'm trying to follow the process in the develop-Branch to install the hello-world example but get the following error:

Downloading from github: https://maven.pkg.github.com/highmed/highmed-dsf/org/highmed/dsf/dsf-tools-pom/0.4.0-SNAPSHOT/maven-metadata.xml
Downloading from sonatype-snapshot: https://oss.sonatype.org/content/repositories/snapshots/org/highmed/dsf/dsf-tools-pom/0.4.0-SNAPSHOT/maven-metadata.xml
Downloaded from github: https://maven.pkg.github.com/highmed/highmed-dsf/org/highmed/dsf/dsf-tools-pom/0.4.0-SNAPSHOT/maven-metadata.xml (1.4 kB at 1.7 kB/s)
Downloading from github: https://maven.pkg.github.com/highmed/highmed-dsf/org/highmed/dsf/dsf-bpe-process-base/0.4.0-SNAPSHOT/dsf-bpe-process-base-0.4.0-SNAPSHOT-tests.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  35.130 s
[INFO] Finished at: 2020-12-23T17:27:02+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project dsf-bpe-process-hello-world: Could not resolve dependencies for project org.highmed.dsf:dsf-bpe-process-hello-world:jar:0.4.0-SNAPSHOT: Could not find artifact org.highmed.dsf:dsf-bpe-process-base:jar:tests:0.4.0-SNAPSHOT in github (https://maven.pkg.github.com/highmed/highmed-dsf) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by wetret** [comment]
Hi Jan,

this is because in the `highmed-dsf` repository, the `PR161` has not yet been merged into the develop branch, and therefore the `dsf-bpe-process-base:jar:tests:0.4.0-SNAPSHOT` is not yet available in the GitHub package registry. The PR will hopefully be merged in the beginning of January.

The first release of the `hello-world process` will then follow with the next DSF release 0.4.0.

There are two solutions: 
- Solution 1: remove the `dsf-bpe-process-base test-jar` from all `pom.xml` and remove the test classes. 
- Solution 2: Checkout in the `highmed-dsf` the branch [issues/160_missing-participating-medics-bug](https://github.com/highmed/highmed-dsf/tree/issues/160_missing-participating-medics-bug) and build the project locally. You should now have the `dsf-bpe-process-base test-jar` in your local `.m2` folder.

I would go with solution 2, since you need the DSF anyway to run the `hello-world process`.

**Comment by janprill** [comment]
Hi Reto, 

I went with Solution 2 and can confirm that the jar gets generated and the build process is working afterwards. Thanks for your help. 

Cheers, Jan
